#spring:
#  profiles: beta #激活环境
spring:
  application:
    name: consumer-01

server:
  port: 9200

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.web.controller: debug

