#spring:
#  profiles: beta #激活环境
spring:
  application:
    name: hadoop
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.36.62:3306/skyDrive?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    host: 47.106.36.62
    port: 6379
    password: redis



    #生成的xml需要在此处注册，（存在bug，实际上使用包.*.xml即可，但是出现了问题）
mybatis:
  mapper-locations:  classpath:sqlMap/ResourcePathMapper.xml
  configuration:
    mapUnderscoreToCamelCase: true



server:
  port: 9200
  
hdfs:
  path: hdfs://47.100.116.155:9000
  username: root

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.web.controller: debug
    com.web.mapper: debug

